# Generated by Django 5.2.3 on 2025-06-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
